title: Mis Retos
description: Los retos que aparecieron en mi vida de desarrollador.
author: Alberth Flores
github: https://github.com/alberthflores
about: I'm Programmer for C# & .Net Core. I've made quite a few web apps, especially on ASP .NET CORE.
disqus_shortname: misretos
google_analytics: UA-XXXXXXXX-Y
avatar: https://avatars1.githubusercontent.com/u/39465063?s=460&v=4

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-twitter
      link: "#"
    - icon: fa-linkedin
      link: "#"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://github.com/alberthflores"

share:
  twitter_username: github.io
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://alberthflores.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
